### ISSUE TITLE
Create an ER diagram for the application

### ISSUE THREAD

**Issue by ruwanliyanage123** [C-O-D-E-H-U-B/Tutor#2]
Create an ER diagram for the Tutor application. Following Entities and Attributes will be the main components

**Student**

- student id
- First Name
- Last Name
- Address
- Email
- Phone Number
- Parent WhatsApp Number
- Date Of Birth

**User**

- display name
- user id
- password
- permissions
- settings
- type
- date of birth
- active status
- profile pic

**Post**

- post id
- posted time date
- type
- active status

**Comment**

- comment id
- comment owner
- comment body
- date time

**Message** 

- Message id
- Message owner
- Message receiver
- Messenger body
- is seen
- date and time

**Assignments**

- Assignment id
- assignment content
- assignment status
- assignee user
- deadline

**Lectures**

- lecture id
- lecture content
- date and time

**Reports**

- report id
- report content
- date and time
- response
- status

**Exam**

- exam id
- content
- owner
- date and time
- duration

**Results**

- user id
- result id
- exam id
- date and time
- marks

**Comment by ruwanliyanage123** [comment]
Removed unnecessary Permission and Settings tables

**Comment by ruwanliyanage123** [comment]
![ER Diagram](https://user-images.githubusercontent.com/30474275/167290803-8383453e-4033-4878-a3fb-f9cc611f35c1.jpg)

**Comment by ruwanliyanage123** [comment]
@melanj can you review this?

**Comment by melanj** [comment]
@ruwanliyanage123 cool, it looks good. 
few questions. 

Who owns "Post" entity?   who can create them?
is given assessment linked to only a given user (student) ? where we store blue print ( template) of a assessment?

**Comment by ruwanliyanage123** [comment]
Post entity create by the one and only admin user. He is the Teacher of the class.
Actually assignments are commo for all users. but we need to track each of them separately, because we hope to present the assignment progress. (Todo and done assignments for each user seperately). then we need to go with the user ids.

**Comment by ruwanliyanage123** [comment]
![ER diagram](https://user-images.githubusercontent.com/30474275/172033958-9d400047-d4b9-43c2-8453-e6710bd0615a.png)
